### ISSUE TITLE
See Attached Image

### ISSUE THREAD

**Issue by brianmillar** [Phillix/arenaFighter#2]
![serveimagejdfhajdkhkdjshf](https://cloud.githubusercontent.com/assets/3112161/9982491/5c02b826-5fd6-11e5-875a-3d8b3f5425ec.png)

**Comment by Phillix** [comment]
lol nice one took me a bit to figure github out, not that its hard once ya know whats what but there was no decent guides,oh i actually watched all the shite ya sent me the other day [😝]  some of it was actually funny but then the rest...  my brain [☹]


________________________________

**Comment by brianmillar** [comment]
Mechanical Keyboard.exe is gold

**Comment by Phillix** [comment]
yeah that and one of the install gentoos was begrudgingly funny :p

**Comment by brianmillar** [comment]
If you slow down one of the install gentoo ones you can use it as a tutorial

**Comment by Phillix** [comment]
i think ill pass thanks! gotta go,talk to ya tomorrow
